name: Build Docker image

on:
  push:
    tags:
    - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set tag for Flutter image
      run: echo "::set-env name=FLUTTER_IMAGE_TAG::$(echo ${{github.ref}} | sed 's/refs\/tags\/*//')"
    - name: Build the Docker image  
      run: docker build . --file Dockerfile --tag dumazyflutter:$FLUTTER_IMAGE_TAG --tag dumazy/flutter:latest
    - name: Test builder
      run: docker run --rm -v "$(pwd)/test/test_project:/src/" dumazy/flutter:$FLUTTER_IMAGE_TAG bash -c "cd /src/ && flutter build apk --pub --release"
    - name: Test tester
      run: docker run --rm -v "$(pwd)/test/test_project:/src/" dumazy/flutter:$FLUTTER_IMAGE_TAG bash -c "cd /src/ && flutter test"
    - name: Login to Github Packages Docker
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Publish the image
      run: docker push dumazy/flutter
      
